# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: railsfun_development

test:
  <<: *default
  database: railsfun_test

production:
  <<: *default
  database: railsfun_production
