# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a1ec753f17ab9e0baf9a8b0dc281dfc57e3c2812680c3434b4c7d9daf4e6136109d8e56db26e2e591c53dd79f90bff9170c36e00560fa64c19f50c95871b5d6

test:
  secret_key_base: ae354c0914a3f0f2765304f21f43e1ca6d448b9b078f15427e40c1671642055ca30bd6e79a7321688fd64f93c407cf8afa27ee9011885a6f20b979cc690bf69d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
